<?
session_name('JOBSESID');
			@session_start();
$_SESSION['fff']="fff";
?>
<!doctype html public "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<title> Job.RusCable.Ru - Работа в электротехнической отрасли России и стран СНГ </title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<META http-equiv="Content-language" content="RU">
<META http-equiv="Expires" content="01 June 1990 GMT">
<META name="title" content="Работа для специалистов кабельной отрасли России и стран СНГ">
<META name="page-type" content="Работа: вакансии и резюме">
<META name="robots" content="index,follow">
<META name="COPYRIGHT" content="Copyright © 2004 RusCable.Ru">
<meta name="description" content="Работа для специалистов кабельной отрасли России и стран СНГ. Поиск резюме. Поиск вакансий.">
<meta name="keywords" content="работа, job, разместить, резюме, вакансия, зарплата, поиск, поиск, работа для Вас, поиск работы">
<link rel="stylesheet" href="http://job.ruscable.ru/style.css" type="text/css">
</head>

<body bgcolor="#ffffff" text="#4574A2" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<center>
<div id="topline_b"  class="banner_oth">
<script type='text/javascript'>
   var m3_u = (location.protocol=='https:'?'https://ruscable.su/www/delivery/ajs.php':'http://ruscable.su/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=52");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
</script><noscript><a href='http://ruscable.su/www/delivery/ck.php?n=a964c228&amp;cb=979879' target='_blank'><img src='http://ruscable.su/www/delivery/avw.php?zoneid=52&amp;cb=979879&amp;n=a964c228' border='0' alt='' /></a></noscript>
</center>	
<noindex><!--Rating@Mail.ru COUNTER--><img height=1 width=1 src="http://db.cd.be.a0.top.list.ru/counter?id=973713"/><!--/COUNTER--></noindex>	

<table border="0" width="100%" height="100%" cellpadding="0" cellspacing="0">
<tr>
	<td height="6" align="center"><img src="http://job.ruscable.ru/images/empty.gif" width="760" height="6" border="0" alt=""></td>
</tr>
<tr>
	<td height="54">
	<table border="0" width="100%" height="54" cellpadding="0" cellspacing="0" background="http://job.ruscable.ru/images/bg-top02.gif">
	<tr>
		<td width="100" align="right" background="/images/bg-top01.gif"><a href="http://job.ruscable.ru/"><img src="http://job.ruscable.ru/images/top-job.gif" width="75" height="54" border=0 alt="Job.RusCable.Ru"></a></td>
		<td width="16" background="http://job.ruscable.ru/images/bg-top01.gif"><img src="http://job.ruscable.ru/images/top-separator.gif" width="16" height="54" border=0 alt=""></td>
		<td width="233"><a href="http://www.ruscable.ru/"><img src="http://job.ruscable.ru/images/top-ruscable.gif" width="233" height="54" border=0 alt="Job.RusCable.Ru"></a></td>
		<td align="right">
		<?
        
        if($_SERVER['REMOTE_ADDR']=="91.206.62.23")
        {
//            var_dump($_SESSION);
//            print ' !2';
        } 
        
		// если пользователь залогинен, то выводим приветствие
		if(isset($_SESSION['user_name']))
		{
			echo '&nbsp;<b>'.@$_SESSION['user_name'].'</b>';
		}
		else
		{
			echo '<img src="/images/empty.gif" width="1" height="1" border="0" alt="">';
		}
		?>
		</td>
		<td width="20"><img src="http://job.ruscable.ru/images/empty.gif" width="20" height="1" border="0" alt=""></td>
	</tr>
	</table>
	</td>
</tr>
<tr>
	<td height="10" align="center"><img src="http://job.ruscable.ru/images/empty.gif" width="1" height="1" border="0" alt=""></td>
</tr>
<tr>
	<td valign="top">
	<table border="0" width="100%" height="100%" cellpadding="0" cellspacing="0">
	<tr>
		<td width="20"><img src="http://job.ruscable.ru/images/empty.gif" width="20" height="1" border="0" alt=""></td>
		<td width="180" valign="top">
			<?include('1-menu.inc');?>
<div visibility=visible display=block>	

<script type="text/javascript" charset="windows-1251"><!--
// размер шрифтов
var yandex_ad_fontSize = 1;

// внешний вид объявлений директа
var yandex_direct_fontColor = "003366";
var yandex_direct_BorderColor = "4574F2";
var yandex_direct_BgColor = "FFFFFF";
var yandex_direct_headerBgColor = "C5DBEA";
var yandex_direct_titleColor = "000066";
var yandex_direct_siteurlColor = "000066";
var yandex_direct_linkColor = "000000";
var yandex_direct_Style = "vertical";

var yandex_r = Math.round(Math.random() * 100000);
document.write('<sc'+'ript type="text/javascript" charset="windows-1251" src="http://bs.yandex.ru/code/8561?rnd='+yandex_r+'&direct-style='+yandex_direct_Style+'"></'+'sc'+'ript>');

function yandex_direct_print(){}
--></script>
<script type="text/javascript">yandex_direct_print()</script>


</div>

		</td>
		<td width="1" bgcolor="#C5DBEA"><img src="http://job.ruscable.ru/images/empty.gif" width="1" height="1" border="0" alt=""></td>
		<td width="20"><img src="http://job.ruscable.ru/images/empty.gif" width="20" height="1" border="0" alt=""></td>
		<td valign="top">
